### ISSUE TITLE
Build failed on ubuntu:16.04, getting error as "ccache.lock: No such file or directory"

### ISSUE THREAD

**Issue by sunil1783** [cloudera/native-toolchain#54]
Build failed on ubuntu:16.04, getting error as "native-toolchain/ccache/ccache.lock: No such file or directory: No such file or directory"

root@d6c77eb423d5:/home/impdev/native-toolchain# ./buildall.sh
++ : generic
++ : generic
++ export BUILD_LABEL
++ set +x
Build ID is 3ddbd51e-c164-448c-8924-e5118576c34a-53d8a71d77
/home/impdev/native-toolchain/ccache
/home/impdev/native-toolchain/functions.sh: line 517: /home/impdev/native-toolchain/ccache/ccache.lock: No such file or directory
root@d6c77eb423d5:/home/impdev/native-toolchain# which ccache
/usr/bin/ccache
root@d6c77eb423d5:/home/impdev/native-toolchain#

**Comment by timarmstrong** [comment]
You can work around by setting DOWNLOAD_CCACHE=0

e.g. DOWNLOAD_CCACHE=0 ./buildall.sh

I'll do a proper fix.

**Comment by timarmstrong** [comment]
Fixed here: https://gerrit.cloudera.org/#/c/13232/
