### ISSUE TITLE
gcc-4.9.2.tar.gz file not full

### ISSUE THREAD

**Issue by aresnasa** [cloudera/native-toolchain#62]
BUILD_HISTORICAL=1 bash -x ./buildall.sh
got tar error

wrong gcc-4.9.2 md5:md5sum source/gcc/gcc-4.9.2.tar.gz 
d67080caeb23464276ba1e95e41734d0  source/gcc/gcc-4.9.2.tar.gz

source gcc-4.9.2 md5:
md5sum source/gcc/gcc-4.9.2.tar.gz 
76f464e0511c26c93425a9dcdc9134cf  source/gcc/gcc-4.9.2.tar.gz

download gcc-4.9.2 from https://ftp.gnu.org/gnu/gcc/gcc-4.9.2/gcc-4.9.2.tar.gz

**Comment by timarmstrong** [comment]
I think removing source/gcc/gcc-4.9.2.tar.gz and rerunning the build script should resolve it. On my system I get 

$ md5sum gcc-4.9.2.tar.gz 
76f464e0511c26c93425a9dcdc9134cf  gcc-4.9.2.tar.gz


It would be nice to automate this...

**Comment by aresnasa** [comment]
Thanks,I redownload the gcc then check the md5sum it works fun.

**Comment by aresnasa** [comment]
> I think removing source/gcc/gcc-4.9.2.tar.gz and rerunning the build script should resolve it. On my system I get
> 
> $ md5sum gcc-4.9.2.tar.gz
> 76f464e0511c26c93425a9dcdc9134cf gcc-4.9.2.tar.gz
> 
> It would be nice to automate this...

Thanks,I redownload the gcc then check the md5sum it works fun.
